apiVersion: v1
kind: ConfigMap
metadata:
  name: gbc-app-config
  labels:
    app: gbc-app
data:
  # アプリケーション基本設定
  APP_PORT: "80"
  APP_HOST: "0.0.0.0"
  LOG_LEVEL: "info"
  DEBUG_MODE: "false"
  
  # サービス接続設定
  SERVICE_TIMEOUT: "30"
  RETRY_COUNT: "3"
  
  # システム設定
  MAX_CONNECTIONS: "100"
  
  # 環境設定
  ENVIRONMENT: "development"
  API_ENDPOINT: "http://api-service"
  
  # HTMLテンプレート用の設定
  app-environment.json: |
    {
      "environment": "development",
      "apiBaseUrl": "http://api-service",
      "features": {
        "enableAnalytics": false,
        "enableNotifications": true
      }
    } 