apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gbc-app-logs-pvc-nfs
spec:
  accessModes:
    - ReadWriteMany  # 複数ノードからアクセス可能
  resources:
    requests:
      storage: 500Mi
  storageClassName: nfs-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gbc-app-db-pvc-nfs
spec:
  accessModes:
    - ReadWriteMany  # 複数ノードからアクセス可能
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage 