apiVersion: v1
kind: Secret
metadata:
  name: gbc-app-secrets-prod
  labels:
    app: gbc-app
    environment: production
type: Opaque
data:
  # 本番環境用データベース接続情報（base64エンコード済み）
  # 注: 実際の環境では、これらの値は外部のシークレット管理システムから取得するか、
  # CI/CDパイプラインで注入することをお勧めします
  DB_HOST: cHJvZC1kYi5leGFtcGxlLmNvbQ==  # prod-db.example.com
  DB_PORT: MzMwNg==  # 3306
  DB_NAME: Z2JjX3Byb2R1Y3Rpb24=  # gbc_production
  DB_USERNAME: cHJvZF91c2Vy  # prod_user
  DB_PASSWORD: c2VjdXJlX3Byb2RfcGFzc3dvcmQ=  # secure_prod_password
  
  # 本番環境用APIキー（base64エンコード済み）
  API_KEY: cHJvZF9hcGlfa2V5X2FiY2RlZjEyMzQ1Njc4OTA=  # prod_api_key_abcdef1234567890
  
  # 本番環境用JWT Secret（base64エンコード済み）
  JWT_SECRET: cHJvZF9qd3Rfc2VjcmV0X2tleV93aXRoX2hpZ2hfZW50cm9weQ==  # prod_jwt_secret_key_with_high_entropy
  
  # 本番環境用SSL証明書（base64エンコード済み）
  # 実際の環境では、有効な証明書と鍵を使用します
  SSL_CERT: LS0tUFJPRFVDVElPTiBDRVJUSUZJQ0FURS0tLQ==  # ---PRODUCTION CERTIFICATE---
  SSL_KEY: LS0tUFJPRFVDVElPTiBLRVktLS0=  # ---PRODUCTION KEY--- 