apiVersion: v1
kind: Secret
metadata:
  name: gbc-app-secrets
  labels:
    app: gbc-app
type: Opaque
data:
  # データベース接続情報（base64エンコード済み）
  # 注: 実際の環境では、これらの値は外部のシークレット管理システムから取得するか、
  # CI/CDパイプラインで注入することをお勧めします
  DB_USERNAME: YWRtaW4=  # admin
  DB_PASSWORD: cGFzc3dvcmQxMjM=  # password123
  
  # APIキー（base64エンコード済み）
  API_KEY: YWJjZGVmMTIzNDU2Nzg5MA==  # abcdef1234567890
  
  # JWT Secret（base64エンコード済み）
  JWT_SECRET: and0X3NlY3JldF9rZXlfZm9yX2diY19hcHA=  # jwt_secret_key_for_gbc_app 