apiVersion: v1
kind: Secret
metadata:
  name: gbc-app-secrets-dev
  labels:
    app: gbc-app
    environment: development
type: Opaque
data:
  # 開発環境用データベース接続情報（base64エンコード済み）
  DB_HOST: bG9jYWxob3N0  # localhost
  DB_PORT: MzMwNg==  # 3306
  DB_NAME: Z2JjX2RldmVsb3BtZW50  # gbc_development
  DB_USERNAME: ZGV2X3VzZXI=  # dev_user
  DB_PASSWORD: ZGV2X3Bhc3N3b3Jk  # dev_password
  
  # 開発環境用APIキー（base64エンコード済み）
  API_KEY: ZGV2X2FwaV9rZXlfMTIzNDU=  # dev_api_key_12345
  
  # 開発環境用JWT Secret（base64エンコード済み）
  JWT_SECRET: ZGV2X2p3dF9zZWNyZXRfa2V5  # dev_jwt_secret_key
  
  # 開発環境用SSL証明書（base64エンコード済み）
  # 実際の環境では、本物の証明書と鍵を使用します
  SSL_CERT: LS0tREVWRUxPUE1FTlQgQ0VSVElGSUNBVEUtLS0=  # ---DEVELOPMENT CERTIFICATE---
  SSL_KEY: LS0tREVWRUxPUE1FTlQgS0VZLS0t  # ---DEVELOPMENT KEY--- 